# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Semaik.
subtitle: 技术博客
description: 直到这一刻微笑着说话为止，我至少留下了一公升眼泪
keywords:
author: Semaik.
language: zh-CN		# 主题语言
timezone: Asia/Shanghai	#中国时区

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: http://example.com		# 绑定域名
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # 默认的新博文名称
default_layout: post	# 默认布局
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false	# 是否显示草稿
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
# theme: landscape
theme: hexo-theme-next

# Deployment
deploy:
  type: 'git'
  repo: https://github.com/semaik/semaik.github.io.git
  branch: master

admin:
  username: zuxuan8@aliyun.com
  password_hash: $2a$10$9RfnbKi6n4AiY2jSTszDlu7PSM3mL1pcpJOKlGIrtuv6kbsECpxCq
  secret: 0000520.
  command: 'sh /blog/hexo/hexo-g.sh'
